name: CI/CD VS Code Extension

on:
  workflow_dispatch:   # 👈 esto habilita el botón "Run workflow" en la pestaña Actions
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Compile extension
        run: npm run compile

      - name: Package extension
        run: npx vsce package

      - name: Publish to Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
